project:
  type: website
  output-dir: docs

website:
  title: "Personal website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About the site
      - href: publications.qmd
        text: Publications
  page-footer: 
    center:
      - text: "#KSE_summerschool"

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

