---
title: "Publications"
author: "HK"
---

# PUBLICATIONS

## Articles

Kutuev P., Yenin M., Zychowicz J., Kurovska H. (2020). Sociological scientific activity and strategies for choosing a research topic in theoretical reflections. National Technical University of Ukraine Journal. Political science. Sociology. Law. No. 3(47) 2020. https://doi.org/10.20535/2308-5053.2020.3(47).227027

Kurovska H. (2022). Application of Basics of Actor-Network Approach to Sociology of Professions. Sociology: Theory, Methods, Marketing. 2022 (1), 196-206.

## Conferences proceedings

Fedorchenko-Kutuev P., Kurovska H. (2022). Higher Education institutions during the COVID-19 pandemic. Матеріали ХI Міжнародної науково-практичної конференції «Сучасні проблеми управління: трансформація публічного управління у постковідному світі» (18-19 листопада 2021 р., м. Київ) \[Proceedings of the XI International Scientific and Practical Conference "Modern problems of governance: the transformation of public administration in the post-ancient world "(November 18-19, 2021, Kyiv)\] pp. 105 - 109

Куровська Г. (2021). COVID-19 та наука в добу ризиків. \[COVID-19 and science in the age of risk\] Соціологія у (пост)сучасності. Збірник тез доповідей XІX Міжнародної наукової конференції студентів, аспірантів, докторантів і молодих вчених (м. Харків, 18-19 березня 2021 р.). \[Sociologyin (post) modernity. Collection of abstracts of the XIX International Scientific Conference of students,graduate students, doctoral students and young scientists (Kharkiv, March 18-19, 2021).\] -- Харків:ХНУ імені В. Н. Каразіна, 2021. С 65

Kurovska H. (2020). Approaches to Science in The Age of Global Challenges. Філософія і науково-технічна творчість у хронотопі технічного університету: Матеріали ІІІ Міжнародної науково-практичної конференції. \[Philosophy and scientific and technical creativity in the chronotope of the Technical University: Proceedings of the III International Scientific and Practical Conference\] Київ, 2020
